server:
  port: 8073
  tomcat:
    uri-encoding: utf-8

spring:
  dubbo:
    application:
      name: search-service
    protocol: dubbo
    registry:
      protocol: zookeeper
      address: 192.168.159.3:2181
    base-package: com.dcxiaolou.tinyJD
  datasource:
    url: jdbc:mysql://localhost:3306/gmall?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 135511
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  elasticsearch:
    jest:
      uris: http://192.168.159.3:9200
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
