server:
  port: 8080
spring:
  dubbo:
    application: user-web
    protocol: dubbo
    registry:
      address: 192.168.159.3:2181
      protocol: zookeeper
    consumer:
      check: false
      timeout: 600000
    base-package: com.dcxiaolou.tinyJD
